### ISSUE TITLE
Did not successfully clear login data of former user. Currently logged in as: , should be: 

### ISSUE THREAD

**Issue by N1C0exe** [DowdyJ/TopGGBotVoter#1]
Hello I have configured all in the config,json file but Im reciving this error . Seems to be a cloudflare problem

**Comment by DowdyJ** [comment]
Did it go away? I know sometimes I would get blocked by cloudflare after about 10 sign-ins in quick succession. Earlier in development I was briefly hit by cloudflare as well, though that went away after about an hour.

**Comment by N1C0exe** [comment]
> Did it go away? I know sometimes I would get blocked by cloudflare after about 10 sign-ins in quick succession. Earlier in development I was briefly hit by cloudflare as well, though that went away after about an hour.

I can try again today . Can u also try againg ? + have u a discord server where we can chat an discuss better ?

![immagine](https://github.com/DowdyJ/TopGG-Bot-Voter/assets/68777539/51a5de30-aabe-472b-a0ac-58a7b6129fe8)

**Comment by DowdyJ** [comment]
I can reproduce the issue. It appears to be a change on top.gg's side. I'll look for a workaround.

**Comment by N1C0exe** [comment]
okay thanks !

**Comment by DowdyJ** [comment]
The issue should be fixed now. There are quite a few more captcha checks than there used to be, so I strongly recommend using 2Captcha. There were major changes made for the Windows version, so be sure to check the instructions. If there are any other issues please let me know!
