### ISSUE TITLE
Websocket keep aborting

### ISSUE THREAD

**Issue by proffessordev** [DowdyJ/TopGGBotVoter#2]
[  SHELL  ] Found Chrome at and using it from
[  SHELL  ] Launching Chromium: with virtual frame buffer...
[  SHELL  ] Failed to get websocket URL. Aborting.

**Comment by Niwatori401** [comment]
First, are you using the Docker version?
Second, try setting "chromeLaunchPause" up to 20 in config.json. That will make it a bit slower, but if the problem is performance related it may fix the issue.

**Comment by DowdyJ** [comment]
It could be a performance issue. Try setting "chromeLaunchPause" up to 20 in config.json. That will make it a bit slower, but if the problem is performance related it may fix the issue.

**Comment by proffessordev** [comment]
> It could be a performance issue. Try setting "chromeLaunchPause" up to 20 in config.json. That will make it a bit slower, but if the problem is performance related it may fix the issue.

i solved this , need one more help can't we login through token instead of email and password

**Comment by DowdyJ** [comment]
From my understanding "logging in" with a token (adding the cookie to the browser session) used to work, but ultimately doesn't anymore due to how either top.gg or Discord authenticate log-ins. One of the features of this project is that it mimics user behavior as closely as possible. This means that it actually types your log in information into the log in form and submits it just like a real user, making it significantly harder to detect. Once this process has been performed once it caches all of the browser data, which should prevent needing to re-sign in more frequently. 

Why do you want to use a token?

**Comment by proffessordev** [comment]
> From my understanding "logging in" with a token (adding the cookie to the browser session) used to work, but ultimately doesn't anymore due to how either top.gg or Discord authenticate log-ins. One of the features of this project is that it mimics user behavior as closely as possible. This means that it actually types your log in information into the log in form and submits it just like a real user, making it significantly harder to detect. Once this process has been performed once it caches all of the browser data, which should prevent needing to re-sign in more frequently.
> 
> Why do you want to use a token?

with email  and password login it everytime ask to verify email

**Comment by DowdyJ** [comment]
Do you mean the "new log in location detected" message? If so, click the link in your email that discord sends. After the first time it won't ask again until you change your IP address substantially.

**Comment by proffessordev** [comment]
> Do you mean the "new log in location detected" message? If so, click the link in your email that discord sends. After the first time it won't ask again until you change your IP address substantially.

its hard when we have 1000+ users account

**Comment by DowdyJ** [comment]
Wow that is a lot of accounts. The only way to [avoid the new login location detection feature of Discord](https://discord.com/blog/keeping-discord-safe-and-sound) is to enable two factor authentication, which I assume isn't a possibility here. The cookies for Chrome are stored in a way that makes manipulating them outside of the browser extremely difficult which rules out creating files with the tokens.

I am fairly certain that top.gg has IP limits for voting, but if that isn't a concern you should only need to go through the sign in process once for each account. In theory you could do this by hand, generating the cache files (tokens) by launching puppeteer's chromium instance with the same flags as the program and signing into Discord. That would be something like this:

node source/getChromiumExecutablePath.js --remote-debugging-port=9222 --disable-gpu --disable-dev-shm-usage --disable-setuid-sandbox --no-first-run --no-sandbox --no-zygote --deterministic-fetch --disable-features=IsolateOrigins --user-data-dir=data/userdata_cache/(YOUR DISCORD USERNAME HERE)

You would need to be running the Linux native solution, not the Docker one to generate the files this way. I would definitely consider just doing the emails though, as that will almost surely be easier.

**Comment by proffessordev** [comment]
> Wow that is a lot of accounts. The only way to [avoid the new login location detection feature of Discord](https://discord.com/blog/keeping-discord-safe-and-sound) is to enable two factor authentication, which I assume isn't a possibility here. The cookies for Chrome are stored in a way that makes manipulating them outside of the browser extremely difficult which rules out creating files with the tokens.
> 
> I am fairly certain that top.gg has IP limits for voting, but if that isn't a concern you should only need to go through the sign in process once for each account. In theory you could do this by hand, generating the cache files (tokens) by launching puppeteer's chromium instance with the same flags as the program and signing into Discord. That would be something like this:
> 
> node source/getChromiumExecutablePath.js --remote-debugging-port=9222 --disable-gpu --disable-dev-shm-usage --disable-setuid-sandbox --no-first-run --no-sandbox --no-zygote --deterministic-fetch --disable-features=IsolateOrigins --user-data-dir=data/userdata_cache/(YOUR DISCORD USERNAME HERE)
> 
> You would need to be running the Linux native solution, not the Docker one to generate the files this way. I would definitely consider just doing the emails though, as that will almost surely be easier.

but some users are login with token and doing votes with email its hard to do large amount of voting

**Comment by DowdyJ** [comment]
Are they using a different voter? If so, can you link to the repository?

**Comment by proffessordev** [comment]
something like this 
https://github.com/healer-op/Tog.gg-Auto-Voter
but this one is outdated

**Comment by DowdyJ** [comment]
That project being (apparently) non-functional is what originally caused me to start this one. I could be wrong, but I am mostly certain that techniques involving adding a log in token directly will not work with how top.gg and Cloudflare authenticate logins and/or are not simpler and more reliable than the current method. I am open to merging a pull request with this feature, but for most users a token is harder to use.
